In [6]:
from astropy.table import Table
import numpy as np
import pandas as pd
import argparse
import os

In [7]:
df = pd.read_csv("../Luis_arzd099bej.csv")

In [8]:
df

,idPNMain,PNG,Name,PNstat,RAJ2000,DECJ2000,DRAJ2000,DDECJ2000,Glon,Glat,...,tbIRFlux_Flux_22um,tbIRFlux_Flux_24um,tbIRFlux_Flux_25um,tbIRFlux_Flux_60um,tbIRFlux_Flux_70um,tbIRFlux_Flux_100um,tbIRFlux_Flux_160um,tbIRFlux_Flux_250um,tbIRFlux_Flux_350um,tbIRFlux_Flux_500um
0,8,000.0+02.0,K 6-4,T,17:37:42.9,-27:49:09.55,264.42886,-27.81932,0.03035,2.06620,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9,000.1-01.9,JaSt 93,T,17:53:23.78,-29:49:45.5,268.34908,-29.82931,0.10451,-1.91213,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10,000.1-08.0,SB 1,T,18:18:48.5,-32:47:55.32,274.70200,-32.79870,0.11982,-8.09701,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11,000.1-01.1,M 3-43,T,17:50:24.3,-29:25:18.70,267.60123,-29.42186,0.12383,-1.14515,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12,000.1+02.6,Al 2-J,T,17:35:35.4,-27:24:04.97,263.89753,-27.40138,0.13036,2.68778,...,NaN,NaN,0.95,1.84,NaN,22.03,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,33609,275.8-08.9,Jonk 1,P,08:52:41.05,-58:36:41.52,133.17104,-58.61153,275.85678,-8.93442,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3879,33637,323.3-06.9,StDr 167,T,16:01:31.96,-61:59:57.81,240.38317,-61.99939,323.34636,-6.91815,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3880,33641,181.0-06.4,Br 3,P,05:24:01.24,24:33:45.90,81.00517,24.56275,181.08554,-6.41726,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3881,33642,032.3-00.5a,Sot 1,P,18:52:16.73,-00:43:39.25,283.06971,-0.72757,32.38023,-0.51884,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3882,33678,084.9+02.1,Br 4,L,20:42:56.03,+45:55:29.70,310.73346,45.92492,84.95503,2.18672,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# Convert the Pandas DataFrame to an Astropy Table
table = Table.from_pandas(df)

In [32]:
# Mask
mask_t = table["PNstat"] == "T"
mask_p = table["PNstat"] == "P"
mask_l = table["PNstat"] == "L"
mask_pl = mask_p + mask_l

table_t = table[mask_t]
table_p = table[mask_p]
table_l = table[mask_l]
table_pl = table[mask_pl]

print("Number of true PN:", len(table_t)) 
print("Number of probable PN:", len(table_p)) 
print("Number of likely PN:", len(table_l)) 
print("Number of probable and likely PN:", len(table_pl))

Number of true PN: 2710
Number of probable PN: 710
Number of likely PN: 463
Number of probable and likely PN: 1173

In [28]:
n_t = len(table_t["RAJ2000"])
sep_t = np.linspace(2.0, 2.0, num=n_t)
ra_t = table_t["DRAJ2000"]
dec_t = table_t["DDECJ2000"]
table_t_ = Table([ra_t, dec_t, sep_t], names=('ra', 'dec', 'radius'), meta={'name': 'first table'})

In [29]:
# Save the file
table_t_.write("../True-PN/tPN-lamostMatch-2arc.dat", format="ascii.commented_header", delimiter=',', overwrite=True)

In [37]:
n_pl = len(table_pl["RAJ2000"])
sep_pl = np.linspace(2.0, 2.0, num=n_pl)
ra_pl = table_pl["DRAJ2000"]
dec_pl = table_pl["DDECJ2000"]
table_pl_ = Table([ra_pl, dec_pl, sep_pl], names=('ra', 'dec', 'radius'), meta={'name': 'first table'})

In [39]:
# Save the file
table_pl_.write("../Likely-Probable-PN/plPN-lamostMatch-2arc.dat", format="ascii.commented_header", delimiter=',', overwrite=True)